// One-time seed: if the "items" collection is empty the first time the app
// connects to your Firestore database, these are written in so the app
// doesn't open blank. Edit or delete entries here before your very first
// load if you want a different starting list — this file is only read once
// (it's ignored on every load after the collection has at least one item).
window.PANTRY_SEED = [
  { id: "poha", name: "Poha", category: "Grains & Starches", stock: "Adequate", location: "" },
  { id: "upma", name: "Upma", category: "Grains & Starches", stock: "Adequate", location: "" },
  { id: "sooji", name: "Sooji", category: "Grains & Starches", stock: "Adequate", location: "" },
  { id: "rice", name: "Rice", category: "Grains & Starches", stock: "Adequate", location: "" },
  { id: "flour", name: "Flour", category: "Grains & Starches", stock: "Adequate", location: "" },
  { id: "besan", name: "Besan", category: "Grains & Starches", stock: "Adequate", location: "" },
  { id: "corn-starch", name: "Corn Starch", category: "Grains & Starches", stock: "Medium", location: "" },
  { id: "quinoa", name: "Quinoa", category: "Grains & Starches", stock: "Adequate", location: "" },
  { id: "sago", name: "Sago", category: "Grains & Starches", stock: "Low", location: "" },
  { id: "pasta-penne-rotini", name: "Pasta (Penne/Rotini)", category: "Grains & Starches", stock: "Adequate", location: "" },
  { id: "spaghetti", name: "Spaghetti", category: "Grains & Starches", stock: "Adequate", location: "" },
  { id: "toor-dal", name: "Toor Dal", category: "Lentils & Legumes", stock: "Adequate", location: "" },
  { id: "urad-dal", name: "Urad Dal", category: "Lentils & Legumes", stock: "Adequate", location: "" },
  { id: "chana-dal", name: "Chana Dal", category: "Lentils & Legumes", stock: "Adequate", location: "" },
  { id: "whole-chana", name: "Whole Chana", category: "Lentils & Legumes", stock: "Adequate", location: "" },
  { id: "rajma", name: "Rajma", category: "Lentils & Legumes", stock: "Adequate", location: "" },
  { id: "muth", name: "Muth", category: "Lentils & Legumes", stock: "Adequate", location: "" },
  { id: "cashew", name: "Cashew", category: "Nuts & Seeds", stock: "Adequate", location: "" },
  { id: "almond", name: "Almond", category: "Nuts & Seeds", stock: "Adequate", location: "" },
  { id: "peanuts", name: "Peanuts", category: "Nuts & Seeds", stock: "Adequate", location: "" },
  { id: "shredded-coconut", name: "Shredded Coconut", category: "Nuts & Seeds", stock: "Adequate", location: "" },
  { id: "oil-peanut", name: "Oil - Peanut", category: "Oils & Vinegar", stock: "Adequate", location: "" },
  { id: "oil-olive", name: "Oil - Olive", category: "Oils & Vinegar", stock: "Adequate", location: "" },
  { id: "sesame-oil", name: "Sesame Oil", category: "Oils & Vinegar", stock: "Adequate", location: "" },
  { id: "vinegar", name: "Vinegar", category: "Oils & Vinegar", stock: "Adequate", location: "" },
  { id: "cinnamon", name: "Cinnamon", category: "Whole Spices", stock: "Adequate", location: "" },
  { id: "cloves", name: "Cloves", category: "Whole Spices", stock: "Adequate", location: "" },
  { id: "bay-leaf", name: "Bay Leaf", category: "Whole Spices", stock: "Adequate", location: "" },
  { id: "fennel-seeds", name: "Fennel Seeds", category: "Whole Spices", stock: "Adequate", location: "" },
  { id: "ajwain", name: "Ajwain", category: "Whole Spices", stock: "Adequate", location: "" },
  { id: "jeera", name: "Jeera", category: "Whole Spices", stock: "Adequate", location: "" },
  { id: "chilli-powder", name: "Chilli Powder", category: "Ground Spices & Masalas", stock: "Adequate", location: "" },
  { id: "garam-masala", name: "Garam Masala", category: "Ground Spices & Masalas", stock: "Adequate", location: "" },
  { id: "turmeric", name: "Turmeric", category: "Ground Spices & Masalas", stock: "Adequate", location: "" },
  { id: "dhana-jeeru", name: "Dhana Jeeru", category: "Ground Spices & Masalas", stock: "Adequate", location: "" },
  { id: "chat-masala", name: "Chat Masala", category: "Ground Spices & Masalas", stock: "Adequate", location: "" },
  { id: "pav-bhaji-masala", name: "Pav Bhaji Masala", category: "Ground Spices & Masalas", stock: "Medium", location: "" },
  { id: "taijin", name: "Taijin", category: "Ground Spices & Masalas", stock: "Adequate", location: "" },
  { id: "garlic", name: "Garlic", category: "Aromatics", stock: "Low", location: "" },
  { id: "soy-sauce", name: "Soy Sauce", category: "Sauces & Condiments", stock: "Adequate", location: "" },
  { id: "hot-sauce", name: "Hot Sauce", category: "Sauces & Condiments", stock: "Low", location: "" },
  { id: "red-chilli-sauce", name: "Red Chilli Sauce", category: "Sauces & Condiments", stock: "Adequate", location: "" },
  { id: "salsa", name: "Salsa", category: "Sauces & Condiments", stock: "Adequate", location: "" },
  { id: "ranch", name: "Ranch", category: "Sauces & Condiments", stock: "Adequate", location: "" },
  { id: "chicken-dipping-sauce", name: "Chicken Dipping Sauce", category: "Sauces & Condiments", stock: "Adequate", location: "" },
  { id: "passata-sauce", name: "Passata Sauce", category: "Sauces & Condiments", stock: "Medium", location: "" },
  { id: "chocolate-syrup", name: "Chocolate Syrup", category: "Sauces & Condiments", stock: "Adequate", location: "" },
  { id: "chicken-stock", name: "Chicken Stock", category: "Stocks & Broths", stock: "Adequate", location: "" },
  { id: "parmesan", name: "Parmesan", category: "Dairy & Cheese", stock: "Adequate", location: "" },
  { id: "kalamata-olives", name: "Kalamata Olives", category: "Pickled & Jarred", stock: "Adequate", location: "" },
  { id: "jalapeno", name: "Jalapeño", category: "Pickled & Jarred", stock: "Adequate", location: "" },
  { id: "sugar", name: "Sugar", category: "Baking & Sweeteners", stock: "Adequate", location: "" },
  { id: "baking-powder", name: "Baking Powder", category: "Baking & Sweeteners", stock: "Adequate", location: "" },
  { id: "crouton", name: "Crouton", category: "Other", stock: "Adequate", location: "" },
  { id: "guacamole-powder", name: "Guacamole Powder", category: "Other", stock: "Adequate", location: "" }
];
